### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by Tobias-08** [hraban/tomono#17]
Hi,
your script does not migrate the existing tags to the monorepo (at least in my case). Do you have any advice how to achieve this?

Thanks!

**Comment by hraban** [comment]
Can you give an example of what you tried?

I just tried with:

```
$ cat repos.txt
git@github.com:ncw/rclone.git rclone
git@github.com:justone/dockviz.git dockviz
```

and I got all tags, from both repos. If anything, that's probably a bad thing; I had never really planned out tag clashes. I just checked, and it turns out all duplicate tag names are ignored, so you'll only be left with the first tag. Is it possible that's what happened on your end?

**Comment by hraban** [comment]
This has been fixed
