### ISSUE TITLE
Empty history for folders

### ISSUE THREAD

**Issue by sevka** [hraban/tomono#37]
Hello, thank you for the script. I'm was playing with it and noticed one issue:
The folder git history is empty. There is only one entry like this created by tomono:
"Merging module-test to master"

I've seen this issue:
https://github.com/hraban/tomono/issues/6
This is strange that this user is able to see the history for the folder, but not for the file.
In my case actually it's empty for both files and folders when I run "git log", but I see the file history when I run it from my IDE. But for the folders, it's always empty. So currently the main problem for me is folder history. 
git blame works fine in CLI and IDE.

Do you think is there any way to fix it?
Is it related to this git bug as well? http://git.661346.n2.nabble.com/git-log-follow-doesn-t-follow-a-rename-over-a-merge-td6480971.html
I tried --follow as well. In this case log is completely empty.

Thank you.

**Comment by hraban** [comment]
Hi, I guess it "kind of" makes sense that you're not seeing a history: afai understand git log by folder is a convenience utility that doesn't actually track folders; it filters the log by files matching that folder. Because the per-project folders are only created by this script, it won't know how to follow it into their pre-monorepo history. This is a side-effect of git not actually caring about folders very much, so I doubt you'll get that fixed any time soon. However, it seems that this is a generic bug ("feature request") in the git tooling, not in this monorepo script. This script just move files and create new folders; the fact that git log --follow doesn't understand how to follow the rename isn't really something I can help with.

See also: https://youtrack.jetbrains.com/issue/IDEA-89370
